import java.util.*
import test
fun main() {
    val input = Scanner(System.`in`)
    val a = input.nextInt()
    var b = input.nextInt()
    var classtest = test()
    println("Program arguments: $a < $b")
    println("Result: ${a < b}")
    println()
    println("Program arguments: $a <= $b")
    println("Result: ${a <= b}")
    println()
    println("Program arguments: $a >= $b")
    println("Result: ${a >= b}")
    println()
    println("Program arguments: $a > $b")
    println("Result: ${a > b}")
    println()
    println("Program arguments: $a + $b")
    println("Result: ${a + b}")
    println()
    println("Program arguments: $a - $b")
    println("Result: ${a - b}")
    println()
    println("Program arguments: $a / $b")
    println("Result: ${a / b}")
    println()
    println("Program arguments: $a * $b")
    println("Result: ${a * b}")
    println()
    println("Program arguments: ${classtest.PI} < $b")
    println("Result: ${classtest.PI} < b}")
    println()
    println("Program arguments: ${classtest.PI} > $b")
    println("Result: ${classtest.PI} > b}")
}