import java.util.*
fun main() {
    val input = Scanner(System.`in`)
    val a = input.nextInt()
    var b = input.nextInt()
    val PI = 3.141592653589793
    println("Program arguments: $a < $b")
    println("Result: ${a < b}")
    println()
    println("Program arguments: $a <= $b")
    println("Result: ${a <= b}")
    println()
    println("Program arguments: $a >= $b")
    println("Result: ${a >= b}")
    println()
    println("Program arguments: $a > $b")
    println("Result: ${a > b}")
    println()
    println("Program arguments: $a + $b")
    println("Result: ${a + b}")
    println()
    println("Program arguments: $a - $b")
    println("Result: ${a - b}")
    println()
    println("Program arguments: $a / $b")
    println("Result: ${a / b}")
    println()
    println("Program arguments: $a * $b")
    println("Result: ${a * b}")
    println()
    println("Program arguments: $PI < $b")
    println("Result: ${PI < b}")
    println()
    println("Program arguments: $PI > $b")
    println("Result: ${PI > b}")
}